# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data Migration Playbook
subtitle: A step-by-step guide for migrating data to a more modern solution.
email: v-raypri@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#url: https://jekylltest.azurewebsites.net
#baseurl: /en-us/sql-server/developer-get-started

disqus:
    shortname: sqlchoice

gitter: https://gitter.im/Microsoft/MigrationPlaybook

steps:
  1: Set up your environment
  2: Migrate your data to $$
  3: Wrap-up and clean-up

menu:
    sqlserver:
        logo: sql-server.png
        pages:
            Azure SQL: sqlserver/azuresql
            sqlserver: sqlserver/sqlserver
    oracle:
        logo: oracle.png
        pages:
           azuresql: oracle/azuresql
           sqlserver: oracle/sqlserver
           azurepostgresql: oracle/azurepostgresql
    db2:
        logo: DB2.png
        pages:
            azuresql: db2/azuresql
            sqlserver: db2/sqlserver
    mysql:
        logo: MySQL.png
        pages:
            azuresql: mysql/azuresql
            sqlserver: mysql/sqlserver
            azuremysql: mysql/azuremysql
    access:
        logo: Access.png
        pages:
            azuresql: access/azuresql
            sqlserver: access/sqlserver
    sybase:
        logo: SAP-ASE.png
        pages:
            azuresql: sybase/azuresql
            sqlserver: sybase/sqlserver
    postgresql:
        logo: PostgreSQL.png
        pages:
            azurepostgresql: postgresql\azurepostgresql
    mongo:
        logo: MongoDB.png
        pages:
            cosmos: mongo\cosmos
    azuretable:
        logo: Azure-Table-Storage.png
        pages:
            cosmos: azuretable\cosmos
            
commonChoices:
    sql-azuresql:
        text: SQL Server => Azure SQL Database
        link: sqlserver/azuresql
    sql-sqlserver:
        text: SQL Server => SQL Server
        link: sqlserver/sqlserver
    oracle-sql:
        text: Oracle => SQL Server
        link: oracle/sqlserver
    db2-sql:
        text: DB2 => Azure SQL Database
        link: db2/azuresql
      
resources:
    sqlserver-csharp:
        pre: Check out what's new with
        text: SQL Server + C# on Channel 9
        link: https://channel9.msdn.com/Events/Connect/2016/151
        condition: C#
    connect:
        pre: Watch more
        text: Connect(); event videos
        link: https://channel9.msdn.com/Events/Connect/2016
    labs:
        pre: Browse our
        text: Virtual Labs Gallery
        link: https://technet.microsoft.com/en-us/virtuallabs

case-studies:
    Floatel:
        title: Floatel International
        text: Maritime Firm Improves Insight and Efficiency with Microsoft Solution
        url: https://customers.microsoft.com/en-us/story/maritime-firm-improves-insight-and-efficiency-with-mic
        logoUrl: https://mpbdevcontent.azureedge.net/Images/FloatelLogo.png
        logoAltText: Floatel
    Infosys:
        title: Infosys
        text: Infosys migrates to SQL server 2016
        url: https://customers.microsoft.com/en-us/story/infosyssql,
        logoUrl: https://mpbdevcontent.azureedge.net/Images/InfosysLogo.png,
        logoAltText: Infosys
    HollandAmerica:
        title: Holland America
        text: "Cruise Line Upgrades BI to Empower Users, Improve Guest Experience, Reduce IT Work"
        url: https://customers.microsoft.com/en-us/story/cruise-line-upgrades-bi-to-empower-users-improve-guest
        logoUrl: https://mpbdevcontent.azureedge.net/Images/HollandAmericaLogo.png
        logoAltText: Holland America

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
